Fix/first quest message flow
BanklessDAO/degen-bankless-dao pull request #20
Opened 2021-11-26 09:23 UTC by tikisailor

Prevent FQ from being triggered twice when invoking /start command (due to transition to event trigger)

2021-11-26 14:30 UTC, amaredeus requested changes
Was thinking about this.. to reduce the complexity and make it super simple. Let's have the first quest start command do two things

1. Removes all first quest related roles
2. Add the first quest start verification role

That should trigger the flow automatically instead of manually trigger

2021-11-26 15:08 UTC, nonsensecodes submitted a review, later dismissed
That was a simple cut. Thank you, @tikisailor! But also, looks like @amaredeus has some suggestions 👍

2021-11-27 04:41 UTC, amaredeus commented
Looks good, let's update the changelog and we should be good with this PR!

2021-11-27 10:42 UTC, tikisailor commented
> Looks good, let's update the changelog and we should be good with this PR!

Ok, please check if this is right. I put the date for release sched on tuesday

2021-11-27 10:42 UTC, tikisailor commented
> Looks good, let's update the changelog and we should be good with this PR!

Ok, please check if this is right. I put the date for release sched on tuesday

2021-11-28 03:52 UTC, amaredeus approved these changes

2021-11-28 04:47 UTC, amaredeus approved these changes

2021-11-28 05:46 UTC, nonsensecodes approved these changes
Looks good! Makes sense to switch from the bang in DMs to slash-commands in the channel. Great job, @tikisailor 🔥

2021-11-28 05:46 UTC, nonsensecodes commented on src/app/service/first-quest/LaunchFirstQuest.ts
> +				'using the **/first-quest start** command');
This makes more sense. Awesome.

2021-11-28 05:46 UTC, merged