remove all first quest related roles upon adding member to server
BanklessDAO/degen-bankless-dao pull request #28
Opened 2021-12-04 16:30 UTC by tikisailor

I hope this fixes the issue that users who re-enter the DAO server while already having FQ roles, receive scrambled FQ messages. Please note that I was not able to test this yet as I could not get through the verification getting triggered on multiple bots. It is fairly simple though and if it is ok with you to merge it into develop I can give it a quick test on Mechanical Animal before release. Thanks @amaredeus for finding this bug.

2021-12-07 17:11 UTC, amaredeus requested changes

2021-12-07 17:11 UTC, amaredeus commented on CHANGELOG.md
> +3. First Quest: bug fix to prevent message scramble in egde case
egde -> edge

2021-12-08 05:22 UTC, nonsensecodes approved these changes
Thank you, @tikisailor!

2021-12-08 05:24 UTC, nonsensecodes requested changes
One more thing: the version number in the `package.json` as requested by @amaredeus

2021-12-08 06:08 UTC, nonsensecodes commented
Requested branch consolidation as more work is incoming.

2021-12-08 06:08 UTC, closed without merging