add opentelemetry and honeycomb exporter
BanklessDAO/degen-bankless-dao pull request #31
Opened 2021-12-05 21:57 UTC by austinmitchem

2021-12-06 16:18 UTC, amaredeus requested changes
Can we update the changelog and the package.json files?

2021-12-07 00:53 UTC, amaredeus requested changes
package.json still needs to be updated. Also GitHub has a request review button that'll help reviewers keep track of what has been updated and needs to be re-reviewed. If you can please hit that button that will be super helpful

2021-12-07 00:55 UTC, amaredeus approved these changes

2021-12-08 06:02 UTC, nonsensecodes approved these changes
Awesome! Thank you for preparing this, @austinmitchem!

2021-12-08 06:02 UTC, merged